In [1]:
import numpy as np
import torch
import pandas as pd

In [6]:
a = torch.ones(4,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
a[1,2]

tensor(1.)

In [13]:
a.unsqueeze(1).shape

torch.Size([4, 1, 3])

In [14]:
a.unsqueeze(1)

tensor([[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])

In [45]:
a.numpy()#[1,1]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [22]:
torch.tensor([[1,2,8],[3,4,7]]).shape

torch.Size([2, 3])

In [24]:
a[None].shape

torch.Size([1, 4, 3])

In [25]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([.3,.5,.2])

In [29]:
img_t*(weights.unsqueeze(-1).unsqueeze(-1))

tensor([[[ 0.0953,  0.2391,  0.0585,  0.2459, -0.4492],
         [ 0.3554, -0.0593, -0.1601, -0.1279, -0.0276],
         [-0.5288,  0.5909,  0.0896, -0.1290,  0.3321],
         [ 0.1235, -0.0260, -0.1890,  0.4411, -0.1401],
         [-0.0060,  0.1961,  0.6677, -0.1195,  0.3490]],

        [[ 0.6183,  0.5357,  0.9996,  0.0206,  0.1172],
         [-0.0290, -0.2000,  0.5563,  0.3849, -0.4023],
         [-0.1462, -0.2682, -0.4987,  0.4171,  0.6248],
         [-0.4077, -0.2179,  1.1108, -0.2285, -0.1406],
         [ 0.2925, -0.2641, -0.8607,  0.6954, -0.1644]],

        [[ 0.2116, -0.1210, -0.1063,  0.2742,  0.0486],
         [ 0.1548, -0.0181,  0.1077, -0.2277,  0.2414],
         [-0.0596,  0.0434, -0.0073,  0.1662, -0.1919],
         [-0.0611,  0.1458,  0.1082, -0.0823, -0.1135],
         [-0.0036, -0.2252, -0.0330,  0.1327, -0.2452]]])

In [42]:
x = (img_t*(weights.unsqueeze(-1).unsqueeze(-1))).sum(-1)

In [43]:
x

tensor([[ 0.1895, -0.0195,  0.3548,  0.2095,  1.0874],
        [ 2.2914,  0.3099,  0.1289,  0.1161, -0.3013],
        [ 0.3070,  0.2582, -0.0492, -0.0029, -0.3744]])

In [44]:
torch.nn.ReLU()(x)

tensor([[0.1895, 0.0000, 0.3548, 0.2095, 1.0874],
        [2.2914, 0.3099, 0.1289, 0.1161, 0.0000],
        [0.3070, 0.2582, 0.0000, 0.0000, 0.0000]])

In [ ]:
torch.transpose()

In [46]:
a.stride()

(3, 1)

In [47]:
a.shape

torch.Size([4, 3])

In [48]:
img_t.stride()

(25, 5, 1)

In [49]:
img_t.transpose(0,1).stride()

(5, 25, 1)

In [2]:
import imageio

In [7]:
img_tr = imageio.imread('G_R2.png')

C:\Users\207894\AppData\Local\Temp\ipykernel_2260\466105678.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_tr = imageio.imread('G_R2.png')


In [8]:
img_tr.shape

(438, 576, 4)

In [11]:
img_tr_ten = torch.from_numpy(img_tr[:,:,0:3])
img_out = img_tr_ten.permute(2,0,1)
img_out.shape

torch.Size([3, 438, 576])

In [22]:
img_out.max(1).values.max(1)


torch.return_types.max(
values=tensor([255, 255, 255], dtype=torch.uint8),
indices=tensor([10, 10, 10]))

In [35]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 438, 576, dtype=torch.uint8)
im = imageio.imread('G_R2.png')
im_t = torch.from_numpy(im)
im_t = im_t.permute(2,0,1)
batch[0] = im_t[:3]

C:\Users\207894\AppData\Local\Temp\ipykernel_2260\1846399992.py:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  im = imageio.imread('G_R2.png')


In [37]:
batch = batch.float()
# batch /=255

In [50]:
torch.mean(batch[:,1]).shape

torch.Size([])

In [53]:
torch.mean(batch[:,1],(1,2))

tensor([ 1.2496, -0.6248, -0.6248])

In [40]:
c_chanels = batch.shape[1]
for i in range(c_chanels):
    mean = torch.mean(batch[:,i])
    std = torch.std(batch[:,i])
    batch[:,i] = (batch[:,i] - mean)/std

In [44]:
batch[1,0]

tensor([[-0.6019, -0.6019, -0.6019,  ..., -0.6019, -0.6019, -0.6019],
        [-0.6019, -0.6019, -0.6019,  ..., -0.6019, -0.6019, -0.6019],
        [-0.6019, -0.6019, -0.6019,  ..., -0.6019, -0.6019, -0.6019],
        ...,
        [-0.6019, -0.6019, -0.6019,  ..., -0.6019, -0.6019, -0.6019],
        [-0.6019, -0.6019, -0.6019,  ..., -0.6019, -0.6019, -0.6019],
        [-0.6019, -0.6019, -0.6019,  ..., -0.6019, -0.6019, -0.6019]])

Tabular data

In [54]:
import csv

In [56]:
win_f = np.loadtxt('winequality-white.csv', dtype=np.float32, delimiter=';', skiprows=1)
win_f

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [77]:
col_list = next(csv.reader(open('winequality-white.csv'), delimiter=';'))
col_list

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [59]:
win_t = torch.from_numpy(win_f)

In [60]:
data = win_t[:,:-1]
target = win_t[:,-1].long()

In [61]:
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [63]:
target_oh = torch.zeros(target.shape[0],10)
target_oh.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [65]:
target.unsqueeze(1).shape

torch.Size([4898, 1])

In [66]:
target.shape

torch.Size([4898])

In [67]:
data_mean = torch.mean(data, 0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [72]:
data_var = torch.var(data, 0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [73]:
data_norm = (data - data_mean)/torch.sqrt(data_var)
data_norm

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [ ]:
bad_indx = target <=3
bad_indx, bad_indx.sum()

(tensor([False, False, False,  ..., False, False, False]), tensor(20))

In [87]:
bad_win = data[target <= 3]
mid_win = data[(target>3)&(target<7)]
good_win = data[target>=7]
bad_mean = torch.mean(bad_win, 0)
mid_mean = torch.mean(mid_win, 0)
good_mean = torch.mean(good_win, 0)

In [88]:
pd.DataFrame.from_records([{'chem':col_list[i],'bad':bad_mean[i].item(),'mid':mid_mean[i].item(),'good':good_mean[i].item()} for i in range(len(col_list)-1)])

chem         bad         mid        good
0          fixed acidity    7.600000    6.886878    6.725142
1       volatile acidity    0.333250    0.281532    0.265349
2            citric acid    0.336000    0.336441    0.326057
3         residual sugar    6.392500    6.705107    5.261509
4              chlorides    0.054300    0.047841    0.038160
5    free sulfur dioxide   53.325001   35.424046   34.550472
6   total sulfur dioxide  170.600006  141.833023  125.245285
7                density    0.994884    0.994471    0.992412
8                     pH    3.187500    3.180812    3.215132
9              sulphates    0.474500    0.487069    0.500142
10               alcohol   10.344999   10.264797   11.416023

In [89]:
torch.lt(data[:,6], 141.83)

tensor([False,  True,  True,  ...,  True,  True,  True])

In [28]:
bc_np = np.loadtxt('hour-fixed.csv', delimiter=',', dtype=np.float32, skiprows=1, converters={1: lambda x: float (x[8:10])})

bc = torch.from_numpy(bc_np)
bc

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
         1.6000e+01],
        [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
         4.0000e+01],
        [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
         3.2000e+01],
        ...,
        [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
         9.0000e+01],
        [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
         6.1000e+01],
        [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
         4.9000e+01]])

In [29]:
bc.shape

torch.Size([17520, 17])

In [30]:
daily_bc = bc.view(-1,24, bc.shape[1])
daily_bc.shape

torch.Size([730, 24, 17])

In [31]:
daily_bc = daily_bc.transpose(1,2)
daily_bc.shape

torch.Size([730, 17, 24])

In [32]:
first_day = bc[:24].long()
weather_oh = torch.zeros(first_day.shape[0],4)
first_day[:,9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [33]:
weather_oh.scatter_(dim=1, index=first_day[:,9].unsqueeze(1).long() -  1, value=1.0)
weather_oh

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [34]:
dayly_weather_oh = torch.zeros(daily_bc.shape[0],4,daily_bc.shape[2])

dayly_weather_oh.scatter_(dim=1, index=daily_bc[:,9,:].unsqueeze(1).long()-1, value=1.0)

dayly_weather_oh[0].shape

torch.Size([4, 24])

In [35]:
daily_bc = torch.cat((daily_bc, dayly_weather_oh), dim = 1)
daily_bc.shape

torch.Size([730, 21, 24])

Simple regression

In [2]:
n = 1000
k = 3.0
c = 4.0
qv = 2.
t_u = (np.random.rand(n)-.5)*20
t_u_e = 0 #(np.random.rand(n)-.5)*1
t_c = t_u*k+c +qv*t_u**2
t_c_e = (np.random.rand(n)-.5)*1
t_c = t_c + t_c_e
t_u = t_u + t_u_e

t_c_f = torch.tensor(t_c, dtype=torch.float32)
t_u_f = torch.tensor(t_u, dtype=torch.float32)


n_samples = t_u_f.shape[0]
n_val = int(n_samples*.2)

shuffled_ind = torch.randperm(n_samples)

train_ind = shuffled_ind[:-n_val]
val_ind = shuffled_ind[-n_val:]
val_ind

t_c = t_c_f[train_ind]
t_u = t_u_f[train_ind]

t_c_v = t_c_f[val_ind]
t_u_v = t_u_f[val_ind]

In [3]:
t_u

tensor([ 6.8683e+00,  3.3297e+00,  6.2703e+00,  9.8839e+00, -1.9243e-01,
        -6.2295e+00, -3.0908e+00,  2.4522e+00,  2.0694e+00, -6.1863e+00,
         4.5819e+00, -5.8140e+00, -2.5445e+00, -2.7108e+00,  7.2806e+00,
         4.2105e+00, -1.4274e+00, -7.5528e+00, -6.0218e+00,  9.9504e+00,
         7.4288e+00, -2.1788e+00, -2.7600e+00, -2.7916e+00, -6.1127e+00,
        -2.8461e+00,  7.4857e+00, -1.9238e+00, -5.3786e+00, -6.1016e+00,
        -8.9933e+00,  3.1010e-01, -5.1371e-01, -3.5956e+00,  5.3628e+00,
         5.0596e+00, -8.7135e+00, -8.1082e+00,  5.9580e+00, -1.9941e+00,
        -3.4489e+00, -5.9005e+00,  9.5011e+00,  8.2236e+00, -6.1692e+00,
         1.2319e+00,  5.7967e+00, -7.1820e+00,  9.0760e+00,  8.2044e+00,
        -2.0986e+00,  1.9712e+00,  3.4868e+00, -6.1318e+00, -5.7928e+00,
        -2.4761e+00, -5.3083e+00,  2.2932e-02, -1.4091e+00,  6.4361e+00,
         6.5689e+00,  2.3206e+00,  8.1982e-01, -2.9681e+00,  8.5425e+00,
         5.8935e+00, -8.4225e+00, -5.3549e+00, -8.0

In [4]:
def model(t_u, w, b):
    return t_u*w + b

def loss_fn(t_p, t_c):
    sq_diff = (t_p - t_c)**2
    return sq_diff.mean()

def dloss_fn(t_p, t_c):
    dfn = 2*(t_p-t_c)/t_p.size(0)
    return dfn

def dmod_w(t_u, w, b):
    return t_u

def dmod_b(t_u, w, b):
    return 1

def grad_fn(t_u, t_c,t_p, w,b):
    dloss = dloss_fn(t_p, t_c)
    dloss_w = dloss*dmod_w(t_u, w, b)
    dloss_b = dloss*dmod_b(t_u, w,b)
    return torch.stack([dloss_w.sum(), dloss_b.sum()])

w = torch.ones(())
b = torch.zeros(())

In [5]:
t_p = model(t_u, w, b)
t_p

tensor([ 6.8683e+00,  3.3297e+00,  6.2703e+00,  9.8839e+00, -1.9243e-01,
        -6.2295e+00, -3.0908e+00,  2.4522e+00,  2.0694e+00, -6.1863e+00,
         4.5819e+00, -5.8140e+00, -2.5445e+00, -2.7108e+00,  7.2806e+00,
         4.2105e+00, -1.4274e+00, -7.5528e+00, -6.0218e+00,  9.9504e+00,
         7.4288e+00, -2.1788e+00, -2.7600e+00, -2.7916e+00, -6.1127e+00,
        -2.8461e+00,  7.4857e+00, -1.9238e+00, -5.3786e+00, -6.1016e+00,
        -8.9933e+00,  3.1010e-01, -5.1371e-01, -3.5956e+00,  5.3628e+00,
         5.0596e+00, -8.7135e+00, -8.1082e+00,  5.9580e+00, -1.9941e+00,
        -3.4489e+00, -5.9005e+00,  9.5011e+00,  8.2236e+00, -6.1692e+00,
         1.2319e+00,  5.7967e+00, -7.1820e+00,  9.0760e+00,  8.2044e+00,
        -2.0986e+00,  1.9712e+00,  3.4868e+00, -6.1318e+00, -5.7928e+00,
        -2.4761e+00, -5.3083e+00,  2.2932e-02, -1.4091e+00,  6.4361e+00,
         6.5689e+00,  2.3206e+00,  8.1982e-01, -2.9681e+00,  8.5425e+00,
         5.8935e+00, -8.4225e+00, -5.3549e+00, -8.0

In [6]:
loss_fn(t_p, t_c)

tensor(8745.9072)

In [7]:
# grad_fn(t_u, t_c, w, b)

In [8]:
l_r = .001

for i in range(100000):
    t_p = model(t_u, w, b)
    grad = grad_fn(t_u, t_c,t_p, w, b)
    w = w - grad[0]*l_r
    b = b - grad[1]*l_r

(w, b)

(tensor(3.6664), tensor(69.6010))

In [9]:
def training_loop(n_epoch, learning_rate, params, t_u, t_c):
    sc = t_c.std()/t_u.std()
    t_u_n = sc*t_u
    for epoch in range(1, n_epoch+1):
        w, b = params
        t_p = model(t_u_n,w,b)
        loss = loss_fn(t_p,t_c)
        grad = grad_fn(t_u_n, t_c,t_p, w, b)
        params = params - learning_rate*grad

        print(f'Epoch {epoch}. Loss: {loss}')
    params[0]*=sc
    return params

In [10]:
training_loop(10000, learning_rate=1e-3, params=torch.tensor([1.,0.]), t_u=t_u, t_c=t_c)

Epoch 1. Loss: 9812.0927734375
Epoch 2. Loss: 78947.203125
Epoch 3. Loss: 3458191.25
Epoch 4. Loss: 168587712.0
Epoch 5. Loss: 8237730816.0
Epoch 6. Loss: 402540789760.0
Epoch 7. Loss: 19670373498880.0
Epoch 8. Loss: 961203346079744.0
Epoch 9. Loss: 4.696972369435034e+16
Epoch 10. Loss: 2.29520083616845e+18
Epoch 11. Loss: 1.1215621135687221e+20
Epoch 12. Loss: 5.480574501735232e+21
Epoch 13. Loss: 2.6781116352760497e+23
Epoch 14. Loss: 1.3086738211816025e+25
Epoch 15. Loss: 6.394906204721424e+26
Epoch 16. Loss: 3.1249051274570263e+28
Epoch 17. Loss: 1.5270019096573382e+30
Epoch 18. Loss: 7.461779333717543e+31
Epoch 19. Loss: 3.6462381857464635e+33
Epoch 20. Loss: 1.7817538278262267e+35
Epoch 21. Loss: inf
Epoch 22. Loss: inf
Epoch 23. Loss: inf
Epoch 24. Loss: inf
Epoch 25. Loss: inf
Epoch 26. Loss: inf
Epoch 27. Loss: inf
Epoch 28. Loss: inf
Epoch 29. Loss: inf
Epoch 30. Loss: inf
Epoch 31. Loss: inf
Epoch 32. Loss: inf
Epoch 33. Loss: inf
Epoch 34. Loss: inf
Epoch 35. Loss: inf
Epoc

tensor([nan, nan])

In [11]:
params=torch.tensor([1.,0.], requires_grad=True)
another = torch.tensor([1.], requires_grad=True)


def model(t_u, w, b, q=0):
    return t_u*w + b + q*t_u**2

def loss_fn(t_p, t_c):
    sq_diff = (t_p - t_c)**2
    return sq_diff.mean()




In [12]:
# loss = loss_fn(model(t_u,*params, another), t_c)
# loss.backward()
# params.grad

In [13]:
another.grad

In [14]:
def training_loop(n_epoch, learning_rate, params, t_u, t_c):
    sc = t_c.std()/t_u.std()
    t_u_n = sc*t_u
    for epoch in range(1, n_epoch+1):
        t_p = model(t_u_n,*params)
        loss = loss_fn(t_p,t_c)
        loss.backward()
        with torch.no_grad():
            params -= learning_rate*params.grad
        params.grad.zero_()

        print(f'Epoch {epoch}. Loss: {loss}')
    with torch.no_grad():
        params[0]*=sc
    return params

In [176]:
training_loop(10000, learning_rate=1e-3, params=torch.tensor([1.,0.], requires_grad=True), t_u=t_u, t_c=t_c)

Epoch 1. Loss: 17.345951080322266
Epoch 2. Loss: 17.04909896850586
Epoch 3. Loss: 16.946887969970703
Epoch 4. Loss: 16.882144927978516
Epoch 5. Loss: 16.824750900268555
Epoch 6. Loss: 16.768943786621094
Epoch 7. Loss: 16.7136173248291
Epoch 8. Loss: 16.658559799194336
Epoch 9. Loss: 16.603723526000977
Epoch 10. Loss: 16.549100875854492
Epoch 11. Loss: 16.494691848754883
Epoch 12. Loss: 16.440488815307617
Epoch 13. Loss: 16.386503219604492
Epoch 14. Loss: 16.33272933959961
Epoch 15. Loss: 16.27916145324707
Epoch 16. Loss: 16.225805282592773
Epoch 17. Loss: 16.172651290893555
Epoch 18. Loss: 16.119705200195312
Epoch 19. Loss: 16.066967010498047
Epoch 20. Loss: 16.014432907104492
Epoch 21. Loss: 15.96210765838623
Epoch 22. Loss: 15.909981727600098
Epoch 23. Loss: 15.85805606842041
Epoch 24. Loss: 15.80633544921875
Epoch 25. Loss: 15.754817962646484
Epoch 26. Loss: 15.70350170135498
Epoch 27. Loss: 15.652382850646973
Epoch 28. Loss: 15.601465225219727
Epoch 29. Loss: 15.550740242004395
Epo

tensor([3.0417, 3.8560], requires_grad=True)

In [15]:
def training_loop(n_epoch, learning_rate, params, t_u, t_c):
    sc = 1#t_c.std()/t_u.std()
    t_u_n = sc*t_u
    optimizer = torch.optim.Adam(params=[params], lr=learning_rate)
    for epoch in range(1, n_epoch+1):
        t_p = model(t_u_n,*params)
        loss = loss_fn(t_p,t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        

        if epoch%1000 == 0:
            print(f'Epoch {epoch}. Loss: {loss}')
    with torch.no_grad():
        params[0]*=sc
    return params

training_loop(10000, learning_rate=1e-2, params=torch.tensor([1.,0.], requires_grad=True), t_u=t_u, t_c=t_c)

Epoch 1000. Loss: 7123.1162109375
Epoch 2000. Loss: 6117.33544921875
Epoch 3000. Loss: 5314.2275390625
Epoch 4000. Loss: 4688.47509765625
Epoch 5000. Loss: 4221.12890625
Epoch 6000. Loss: 3895.302490234375
Epoch 7000. Loss: 3692.1298828125
Epoch 8000. Loss: 3587.171142578125
Epoch 9000. Loss: 3548.3505859375
Epoch 10000. Loss: 3540.54150390625


tensor([ 3.6741, 68.8676], requires_grad=True)

In [16]:
def training_loop(n_epoch, learning_rate, params, t_u, t_c, t_u_v, t_c_v):
    sc = 1#t_c.std()/t_u.std()
    t_u_n = sc*t_u
    optimizer = torch.optim.Adam(params=[params], lr=learning_rate)
    for epoch in range(1, n_epoch+1):
        t_p = model(t_u_n,*params)
        loss = loss_fn(t_p,t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        with torch.no_grad():
            t_p = model(t_u_v*sc,*params)
            val_loss = loss_fn(t_p,t_c_v)

        

        if epoch%10000 == 0:
            print(f'Epoch {epoch}. Loss: {loss} Val loss: {val_loss}')
    with torch.no_grad():
        params[0]*=sc
    return params

training_loop(50000, learning_rate=1e-3, params=torch.tensor([1.,1.,1.], requires_grad=True), t_u=t_u, t_c=t_c, t_u_v=t_u_v, t_c_v=t_c_v)

Epoch 10000. Loss: 0.08341310173273087 Val loss: 0.07744727283716202
Epoch 20000. Loss: 0.0822068527340889 Val loss: 0.07650033384561539
Epoch 30000. Loss: 0.08220762014389038 Val loss: 0.07644817233085632
Epoch 40000. Loss: 0.08220682293176651 Val loss: 0.0765032172203064
Epoch 50000. Loss: 0.08220675587654114 Val loss: 0.07649458199739456


tensor([2.9993, 3.9858, 2.0003], requires_grad=True)

In [17]:
def training_loop(n_epoch, learning_rate, params, t_u, t_c, t_u_v, t_c_v):
    sc = 1#t_c.std()/t_u.std()
    t_u_n = sc*t_u
    optimizer = torch.optim.Adam(params=[params], lr=learning_rate)
    for epoch in range(1, n_epoch+1):
        t_p = model(t_u_n,*params)
        loss = loss_fn(t_p,t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        with torch.no_grad():
            t_p = model(t_u_v*sc,*params)
            val_loss = loss_fn(t_p,t_c_v)

        

        if epoch%10000 == 0:
            print(f'Epoch {epoch}. Loss: {loss} Val loss: {val_loss}')
    with torch.no_grad():
        params[0]*=sc
    return params

training_loop(50000, learning_rate=1e-3, params=torch.tensor([1.,1.], requires_grad=True), t_u=t_u, t_c=t_c, t_u_v=t_u_v, t_c_v=t_c_v)

Epoch 10000. Loss: 6978.7861328125 Val loss: 6989.857421875
Epoch 20000. Loss: 5925.1923828125 Val loss: 5950.85009765625
Epoch 30000. Loss: 5066.748046875 Val loss: 5107.8779296875
Epoch 40000. Loss: 4402.7568359375 Val loss: 4460.16357421875
Epoch 50000. Loss: 3931.038330078125 Val loss: 4005.441162109375


tensor([ 3.8728, 49.7938], requires_grad=True)

In [18]:
def training_loop(n_epoch, learning_rate, params, t_u, t_c, t_u_v, t_c_v):
    sc = 1#t_c.std()/t_u.std()
    t_u_n = sc*t_u
    optimizer = torch.optim.Adam(params=[params], lr=learning_rate)
    for epoch in range(1, n_epoch+1):
        t_p = model(t_u_n,*params)
        loss = loss_fn(t_p,t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        with torch.no_grad():
            t_p = model(t_u_v*sc,*params)
            val_loss = loss_fn(t_p,t_c_v)

        

        if epoch%10000 == 0:
            print(f'Epoch {epoch}. Loss: {loss} Val loss: {val_loss}')
    with torch.no_grad():
        params[0]*=sc
    return params

training_loop(50000, learning_rate=1e-3, params=torch.tensor([1.,1.,1.], requires_grad=True), t_u=t_u, t_c=t_c, t_u_v=t_u_v, t_c_v=t_c_v)

Epoch 10000. Loss: 0.08341310173273087 Val loss: 0.07744727283716202
Epoch 20000. Loss: 0.0822068527340889 Val loss: 0.07650033384561539
Epoch 30000. Loss: 0.08220762014389038 Val loss: 0.07644817233085632
Epoch 40000. Loss: 0.08220682293176651 Val loss: 0.0765032172203064
Epoch 50000. Loss: 0.08220675587654114 Val loss: 0.07649458199739456


tensor([2.9993, 3.9858, 2.0003], requires_grad=True)

In [19]:
x = torch.ones(10,1)

lin_mod = torch.nn.Linear(1,1)
lin_mod(x)

tensor([[-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733],
        [-0.2733]], grad_fn=<AddmmBackward0>)

In [20]:
def training_loop(n_epoch, model, loss_fn, learning_rate, t_u, t_c, t_u_v, t_c_v):
    sc = 1#t_c.std()/t_u.std()
    t_u_n = sc*t_u
    optimizer = torch.optim.Adam(params=model.parameters(), lr=learning_rate)
    for epoch in range(1, n_epoch+1):
        t_p = model(t_u_n)
        loss = loss_fn(t_p,t_c)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        with torch.no_grad():
            t_p = model(t_u_v*sc)
            val_loss = loss_fn(t_p,t_c_v)

        

        if epoch==1 or epoch%10000 == 0:
            print(f'Epoch {epoch}. Loss: {loss} Val loss: {val_loss}')
    # with torch.no_grad():
    #     params[0]*=sc
    return list(model.parameters())

l_model = torch.nn.Linear(1,1)
training_loop(50000, model=l_model,loss_fn=torch.nn.MSELoss(), learning_rate=1e-3, t_u=t_u.unsqueeze(1), t_c=t_c.unsqueeze(1), t_u_v=t_u_v.unsqueeze(1), t_c_v=t_c_v.unsqueeze(1))

Epoch 1. Loss: 9189.4140625 Val loss: 8991.419921875
Epoch 10000. Loss: 7213.0087890625 Val loss: 7221.2939453125
Epoch 20000. Loss: 6120.20361328125 Val loss: 6142.8701171875
Epoch 30000. Loss: 5222.908203125 Val loss: 5260.87353515625
Epoch 40000. Loss: 4520.13671875 Val loss: 4574.22509765625
Epoch 50000. Loss: 4010.11376953125 Val loss: 4081.068359375


[Parameter containing:
 tensor([[3.8927]], requires_grad=True),
 Parameter containing:
 tensor([47.8829], requires_grad=True)]

In [21]:
seq_model = torch.nn.Sequential(torch.nn.Linear(1,13), torch.nn.Tanh(),torch.nn.Linear(13,1))
training_loop(50000, model=seq_model,loss_fn=torch.nn.MSELoss(), learning_rate=1e-3, t_u=t_u.unsqueeze(1), t_c=t_c.unsqueeze(1), t_u_v=t_u_v.unsqueeze(1), t_c_v=t_c_v.unsqueeze(1))

Epoch 1. Loss: 9029.8671875 Val loss: 8842.4208984375
Epoch 10000. Loss: 2033.921875 Val loss: 2139.073974609375
Epoch 20000. Loss: 847.182861328125 Val loss: 913.170654296875
Epoch 30000. Loss: 71.2941665649414 Val loss: 74.95067596435547
Epoch 40000. Loss: 0.8127864003181458 Val loss: 0.8093621730804443
Epoch 50000. Loss: 0.1344386339187622 Val loss: 0.1414448469877243


[Parameter containing:
 tensor([[-0.3618],
         [ 0.7753],
         [ 0.0123],
         [ 0.3688],
         [ 1.2587],
         [ 0.5735],
         [ 0.5270],
         [-0.0118],
         [-0.8920],
         [ 0.0124],
         [ 0.0123],
         [-0.0127],
         [ 0.0129]], requires_grad=True),
 Parameter containing:
 tensor([  1.1617,  -6.3145,  -6.0971,   1.7209, -12.0985,   4.2911,  -3.2102,
           6.5137,  -8.4966,  -5.9646,  -6.0098,   6.3415,  -6.3460],
        requires_grad=True),
 Parameter containing:
 tensor([[-35.5684,  32.1347, -32.1272, -35.4581,  24.8880, -33.8170,  35.3363,
           32.1555,  31.4398, -32.0615, -32.0903,  32.3399, -31.9260]],
        requires_grad=True),
 Parameter containing:
 tensor([31.4257], requires_grad=True)]

In [268]:
a = np.array([1,1,0])
b = np.array([-1,1,0])
for i in range(len(a)-1):
    a2=a[i:i+2]
    a2_norm = np.sqrt(np.sum(a2**2))
    a2n = a2/a2_norm
    b2=b[i:i+2]
    b2_norm = np.sqrt(np.sum(b2**2))
    b2n=b2/b2_norm
    print(np.arccos(a2n.dot(b2n))/np.pi*180)



90.0
0.0
